name: CI 
on: 
  push:
    branches:
     - main
env:
  BAZELISK_VERSION: v1.17.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 6.2.1
        with:
          path: | 
            ~/.cache/bazel
          key: ${{ runner.os }}-bazelisk-${{ env.BAZELISK_VERSION }}-bazel-cache

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/$BAZELISK_VERSION/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Run tests
        run: bazel test --test_output=all //...

      # - name: Run integration tests
      #   run: bazel run //integration/...

      - name: Run build
        run: bazel build //...
